### ISSUE TITLE
Proposition: Add ability to set default commands on terminal startup

### ISSUE THREAD

**Issue by WiktorOgrodnik** [Ph0enixKM/Illiade#2]
This can be useful for changing the default zsh to bash.

**Comment by ghost** [comment]
very good idea!

**Comment by Ph0enixKM** [comment]
Really good idea since Illiade's DNA lacks of a lot of features. Added in Terminal section.
Here is a quick preview of what I've been able to achieve
![Screenshot_20210402_145740](https://user-images.githubusercontent.com/29208124/113417529-e1bb8200-93c3-11eb-97d8-0edea0e5859f.png)

_( Here is a working terminal example screenshot )_

![Screenshot_20210402_145907](https://user-images.githubusercontent.com/29208124/113417578-fac43300-93c3-11eb-8ad6-7667b13316aa.png)
---
Published and distributed as a version **1.3.12**. Ready to download from _.deb_ package and from readme installer snippet. 🎉
